rules:
  - id: detect-hardcoded-password
    message: "Hardcoded password detected."
    severity: ERROR
    languages:
      - javascript
      - typescript
    patterns:
      - pattern-either:
          - pattern: password = "..."
          - pattern: password = '...'
          - pattern: const password = "..."
          - pattern: const password = '...'
    metadata:
      category: security
      owasp:
        - A02:2021-Cryptographic Failures
      cwe:
        - "CWE-798"
