env:
  contexts:
    - name: JuiceShop
      urls:
        - http://juice-shop-dast:3000
      includePaths:
        - http://juice-shop-dast:3000.*
      excludePaths:
        - http://juice-shop-dast:3000/rest/user/logout.*
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: replacer
    parameters:
      deleteAllRules: true
    rules:
      - description: Juice Shop ephemeral bearer token
        url: http://juice-shop-dast:3000.*
        matchType: req_header
        matchString: Authorization
        matchRegex: false
        replacementString: Bearer ${ZAP_AUTH_TOKEN}

  - type: openapi
    parameters:
      apiFile: /zap/wrk/.github/zap/juice-shop-openapi.yaml
      context: JuiceShop
      targetUrl: http://juice-shop-dast:3000

  - type: spider
    parameters:
      context: JuiceShop
      maxDuration: 1
      maxDepth: 5

  - type: passiveScan-wait
    parameters:
      maxDuration: 1

  - type: activeScan
    parameters:
      context: JuiceShop
      maxScanDurationInMins: 3

  - type: passiveScan-wait
    parameters:
      maxDuration: 1

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk/.github/zap/reports
      reportFile: zap-report.html
      reportTitle: Juice Shop Authenticated DAST
    alwaysRun: true

  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/wrk/.github/zap/reports
      reportFile: zap-report.json
      reportTitle: Juice Shop Authenticated DAST
    alwaysRun: true

  - type: exitStatus
    parameters:
      errorLevel: High
      okExitValue: 0
      warnExitValue: 0
      errorExitValue: 1
    alwaysRun: true
