name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  project-information:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config auto --config .github/semgrep-rules .

      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: CRITICAL,HIGH
          exit-code: 0
      - name: Generate CycloneDX SBOM
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: cyclonedx
          output: sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: sbom.json
      - name: Build Docker Image
        run: docker build --tag juice-shop:local .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: juice-shop:local
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 0

      - name: Project Information
        run: |
          echo "====================================="
          echo " Secure DevSecOps Pipeline"
          echo "====================================="
          echo "Repository:"
          pwd
          ls -la

